##########################################################################
# 部署配置文件(common)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # 数据库
  mysql:
    image: harbor.gdxw.com/library/mysql:5.6
    container_name: "${ENV_PREFIX}-common-mysql"
    hostname: "${ENV_PREFIX}-common-mysql"
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/mysql/conf:/etc/mysql/conf.d:ro
      - ./volume/mysql/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      mynet:
        ipv4_address: 172.16.100.10
  # 数据库
  mysql3:
    image: harbor.gdxw.com/library/mysql:8.0
    container_name: "${ENV_PREFIX}-common-mysql3"
    hostname: "${ENV_PREFIX}-common-mysql"
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/mysql/conf:/etc/mysql/conf.d:ro
      - ./volume/mysql/data:/var/lib/mysql:rw
    ports:
      - "3308:3306"
    networks:
      mynet:
        ipv4_address: 172.16.100.12
  # 消息队列
  rabbitmq:
    image: harbor.gdxw.com/library/rabbitmq:3.6
    container_name: "${ENV_PREFIX}-common-rabbitmq"
    hostname: "${ENV_PREFIX}-common-rabbitmq"
    restart: "always"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/rabbitmq/data:/var/lib/rabbitmq:rw
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      mynet:
        ipv4_address: 172.16.100.20
  # 缓存服务
  redis:
    image: harbor.gdxw.com/library/redis:3.2
    container_name: "${ENV_PREFIX}-common-redis"
    hostname: "${ENV_PREFIX}-common-redis"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/redis/conf/redis.conf:/etc/redis/redis.conf:ro
      - ./volume/redis/data:/data:rw
    ports:
      - "6379:6379"
    networks:
      mynet:
        ipv4_address: 172.16.100.30
  # ZOOKEEPER
  zookeeper1:
    image: harbor.gdxw.com/library/zookeeper:3.4
    container_name: "${ENV_PREFIX}-common-zookeeper1"
    hostname: "${ENV_PREFIX}-common-zookeeper1"
    restart: "always"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2181:2181"
    networks:
      mynet:
        ipv4_address: 172.16.100.41
  # ZOOKEEPER
  zookeeper2:
    image: harbor.gdxw.com/library/zookeeper:3.4
    container_name: "${ENV_PREFIX}-common-zookeeper2"
    hostname: "${ENV_PREFIX}-common-zookeeper2"
    restart: "always"
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2182:2181"
    networks:
      mynet:
        ipv4_address: 172.16.100.42
  # ZOOKEEPER
  zookeeper3:
    image: harbor.gdxw.com/library/zookeeper:3.4
    container_name: "${ENV_PREFIX}-common-zookeeper3"
    hostname: "${ENV_PREFIX}-common-zookeeper3"
    restart: "always"
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2183:2181"
    networks:
      mynet:
        ipv4_address: 172.16.100.43
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"