##########################################################################
# 部署配置文件(icm)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # icm proxy
  icm-proxy:
    image: harbor.gdxw.com/library/nginx:1.12
    container_name: "${ENV_PREFIX}-icm-proxy"
    hostname: "${ENV_PREFIX}-icm-proxy"
    restart: "always"
    environment:
      - PROXY_HOST1=172.16.120.11
      - PROXY_PORT1=9060
      - PROXY_HOST2=172.16.120.12
      - PROXY_PORT2=9060
    volumes:
      - ./volume/icm-proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volume/icm-proxy/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./volume/icm-proxy/conf/upstream.temp:/etc/nginx/conf.d/upstream.temp:ro
      - ./volume/icm-proxy/script/docker-entrypoint.sh:/docker-entrypoint.sh
    entrypoint: /docker-entrypoint.sh
    command: nginx -g 'daemon off;'
    ports:
      - "8180:80"
    networks:
      mynet:
        ipv4_address: 172.16.120.10
  # icm web1
  icm-web1:
    image: harbor.gdxw.com/gdxw/nms-icm-web:${ICM_WEB_VERSION}
    container_name: "${ENV_PREFIX}-icm-web1"
    hostname: "${ENV_PREFIX}-icm-web1"
    restart: "always"
    environment:
      - RMI_REGISTRY_IP=${HOST_IP}
      - JMX_REGISTRY_PORT=11001
      - JMX_SERVICE_PORT=11002
      - JDBC_HOST=192.168.100.200
      - JDBC_PORT=3306
      - JDBC_DATABASE=ginms
      - JDBC_USERNAME=root
      - JDBC_PASSWORD=root
      - ZK_ADDRESS=${HOST_IP}:2181
      - GCLM_AREA=wuhou
      - MQ_HOST=${HOST_IP}
      - MQ_PORT=5672
      - MQ_USER=icm
      - MQ_PASS=icm
      - MQ_VHOST=/icm
    env_file:
      - ./volume/icm-web/env/default.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/icm-web/logs:/home/gdxw/gdxw-base/logs:rw
      - ./volume/icm-web/conf/wrapper-java-additional.temp:/home/gdxw/gdxw-base/conf/wrapper/wrapper-java-additional.temp:ro
      - ./volume/icm-web/script/docker-entrypoint.sh:/docker-entrypoint.sh
    entrypoint: /docker-entrypoint.sh
    command: /home/gdxw/gdxw-base/bin/gdxwcli.sh console
    ports:
      - "9060:9060"
      - "11001:11001"
      - "11002:11002"
    networks:
      mynet:
        ipv4_address: 172.16.120.11
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.120.0/24"