version: "2"
services:
  nginx:
    image: harbor.gdxw.com/library/nginx:1.12
    container_name: "dev-nginx"
    hostname: "nginx"
    restart: "always"
    environment:
      - PROXY_HOST1=127.0.0.1
      - PROXY_PORT1=8081
      - PROXY_HOST2=127.0.0.1
      - PROXY_PORT2=8082
    volumes:
      - ./volume/nginx/template/upstream.template:/etc/nginx/conf.d/upstream.template:ro
      - ./volume/nginx/conf/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/upstream.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "8000:80"
    networks:
      - devnet
  mysql:
    image: harbor.gdxw.com/library/mysql:5.6
    container_name: "dev-mysql"
    hostname: "mysql"
    restart: "always"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/mysql/conf:/etc/mysql/conf.d:ro
      - ./volume/mysql/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    networks:
      - devnet
  rabbitmq:
    image: harbor.gdxw.com/library/rabbitmq:3.6
    container_name: "dev-rabbitmq"
    hostname: "rabbitmq"
    restart: "always"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitmq
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/rabbitmq/data:/var/lib/rabbitmq:rw
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - devnet
  redis:
    image: harbor.gdxw.com/library/redis:3.2
    container_name: "dev-redis"
    hostname: "redis"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/redis/conf/redis.conf:/etc/redis/redis.conf:ro
      - ./volume/redis/data:/data:rw
    ports:
      - "6379:6379"
    networks:
      - devnet
  zookeeper1:
    image: harbor.gdxw.com/library/zookeeper:3.4
    container_name: "dev-zookeeper-1"
    hostname: "zookeeper"
    restart: "always"
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2181:2181"
    networks:
      - devnet
  zookeeper2:
    image: harbor.gdxw.com/library/zookeeper:3.4
    container_name: "dev-zookeeper-2"
    hostname: "zookeeper"
    restart: "always"
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2182:2181"
    networks:
      - devnet
  zookeeper3:
    image: harbor.gdxw.com/library/zookeeper:3.4
    container_name: "dev-zookeeper-3"
    hostname: "zookeeper"
    restart: "always"
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2183:2181"
    networks:
      - devnet
  oracle-ee-11g:
    image: harbor.gdxw.com/gdxw/oracle-ee-11g:database
    container_name: "dev-oracle-ee-11g"
    hostname: "database"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "10022:22"
      - "11521:1521"
    networks:
      - devnet
networks:
  devnet:
    driver: bridge
    external: false
